/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControladorCorreo;
import Controlador.ControladorRevision;
import Modelo.Correo;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.String;
import java.util.Iterator;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Auxiliar
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    DefaultTableModel dtm = new DefaultTableModel();

    public menuPrincipal() {
        initComponents();
        this.setSize(700, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        ImageIcon i = new ImageIcon(getClass().getResource("/Iconos/icons8-email-64.png"));
        ImageIcon carga = new ImageIcon(getClass().getResource("/Iconos/Spinner.gif"));
        btnEnviarcorreo.setCursor(new Cursor(HAND_CURSOR));
        Image i2 = i.getImage();
        this.setIconImage(i2);
        spinnerF.setSize(43, 43);
        Image spinner = carga.getImage().getScaledInstance(spinnerF.getWidth(), spinnerF.getHeight(), Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(spinner);
        spinnerF.setIcon(icon);
        
        dtm.addColumn("placa");
        dtm.addColumn("fecha revision");
        dtm.addColumn("Correo cliente");
        Correo.setBorder(new EmptyBorder(5, 10, 5, 10));
        jMenu1.setCursor(new Cursor(HAND_CURSOR));
        Correo.setCursor(new Cursor(HAND_CURSOR));
        try {
            UIManager.setLookAndFeel(new FlatArcIJTheme());
            UIManager.put("Component.arrowType", "chevron");
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
            UIManager.put("ScrollBar.trackInsets", new Insets(2, 4, 2, 4));
            UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
            UIManager.put("ScrollBar.track", new Color(0xe0e0e0));
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviarcorreo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnvios = new javax.swing.JTable();
        spinnerF = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Correo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviarcorreo.setText("Enviar");
        btnEnviarcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarcorreoActionPerformed(evt);
            }
        });

        tblEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEnvios);

        spinnerF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Spinner.gif"))); // NOI18N

        jMenu1.setText("| Parametros |");

        Correo.setText("Correo");
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jMenu1.add(Correo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnviarcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnEnviarcorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spinnerF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        VistaCorreo v = new VistaCorreo();
        v.setVisible(true);
    }//GEN-LAST:event_CorreoActionPerformed

    private void btnEnviarcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarcorreoActionPerformed
        //necesito enviar smtp, puerto, vehiculo, asunto, placa, correo, fecha de revision
        ControladorRevision cr = new ControladorRevision();
        Correo c = ControladorCorreo.BuscarCoreo();
        ArrayList l;

        tblEnvios.setModel(dtm);
        //tblEnvios.setDefaultEditor(Object.class, null);
        boolean gmail = false;
        if (c != null) {
            try {
                l = cr.buscarVehiculo();
                String tem[] = null;
                if (c.getCorreo().contains("@gmail.com")) {
                    gmail = true;
                }

                if (c.getCorreo().contains("@hotmail.com")) {
                    gmail = false;
                }

                Iterator it = l.iterator();
                while (it.hasNext()) {
                    //System.out.println(it.next().toString());
                    tem = it.next().toString().split(";");
                    //System.out.println(tem[2].toString());
                    if (gmail == true) {
                        ControladorCorreo.enviarCorreo("smtp.gmail.com", "587", tem[0].toString(), c.getAsunto(), tem[2].toString(), tem[1].toString());
                        //System.out.println("smtp.gmail.com"+ "587" + tem[0].toString()+ c.getAsunto()+ tem[2].toString()+ tem[1].toString());
                    }

                    if (gmail == false) {
                        ControladorCorreo.enviarCorreo("smtp.live.com", "25", tem[0].toString(), c.getAsunto(), tem[2].toString(), tem[1].toString());
                    }
                }

                JOptionPane.showMessageDialog(null,"Enviados con exito");

                for (int i = 0; i < l.size(); i++) {
                    String tempo[] = null;
                    tempo = l.get(i).toString().split(";");
                    dtm.addRow(tempo);
                }
            } catch (SQLException ex) {
                Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnviarcorreoActionPerformed

    public void iconImage(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Correo;
    private javax.swing.JButton btnEnviarcorreo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel spinnerF;
    private javax.swing.JTable tblEnvios;
    // End of variables declaration//GEN-END:variables
}
