/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.ControladorAltiria;
import Controlador.ControladorCorreo;
import Modelo.Correo;
import Modelo.Mensaje;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Auxiliar
 */
public class VistaMensaje2 extends javax.swing.JFrame {

    /**
     * Creates new form VistaCorreo
     */
    public VistaMensaje2() {
        initComponents();
        this.setTitle("Agregar Credenciales Altria");
        iniciar();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AgregarMensaje.setCursor(new Cursor(HAND_CURSOR));
        ImageIcon i = new ImageIcon(getClass().getResource("/Iconos/icons8-email-64.png"));
        Image i2 = i.getImage();
        this.setIconImage(i2);
        /*
        try {
            UIManager.setLookAndFeel(new FlatArcIJTheme());
            UIManager.put("Component.arrowType", "chevron");
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
            UIManager.put("ScrollBar.trackInsets", new Insets(2, 4, 2, 4));
            UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
            UIManager.put("ScrollBar.track", new Color(0xe0e0e0));
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCorreoMensaje = new javax.swing.JTextField();
        AgregarMensaje = new javax.swing.JButton();
        txtPasswordMensaje = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        longitudTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Contraseña:");

        txtCorreoMensaje.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCorreoMensaje.setBorder(null);

        AgregarMensaje.setText("Agregar");
        AgregarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMensajeActionPerformed(evt);
            }
        });

        txtPasswordMensaje.setFont(txtPasswordMensaje.getFont().deriveFont(txtPasswordMensaje.getFont().getSize()+7f));
        txtPasswordMensaje.setBorder(null);
        txtPasswordMensaje.setCaretColor(new java.awt.Color(73, 181, 172));
        txtPasswordMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordMensajeActionPerformed(evt);
            }
        });

        jLabel3.setText("Mensaje:");

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        txtMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMensajeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtMensaje);

        jLabel4.setText("Longitud:");

        longitudTxt.setText("               ");

        jLabel1.setText("Correo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgregarMensaje)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPasswordMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longitudTxt))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPasswordMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(longitudTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarMensaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMensajeActionPerformed
        // TODO add your handling code here:
        if (!txtCorreoMensaje.getText().equals("") && !txtPasswordMensaje.getText().equals("") && !txtMensaje.getText().equals("")) {
            if (txtMensaje.getText().trim().length() > 160) {
                JOptionPane.showMessageDialog(null, "Mensaje debe ser menor a 160 caracteres", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                ControladorAltiria.AgregerMensaje(txtCorreoMensaje.getText().trim(), txtPasswordMensaje.getText().trim(), txtMensaje.getText().trim());
                JOptionPane.showMessageDialog(null, "Actualizado con exito");
                this.dispose();
            }
        }
    }//GEN-LAST:event_AgregarMensajeActionPerformed

    private void txtPasswordMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordMensajeActionPerformed

    }//GEN-LAST:event_txtPasswordMensajeActionPerformed

    private void txtMensajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensajeKeyTyped
        // TODO add your handling code here:
        Border line = BorderFactory.createLineBorder(Color.RED, 2);
        Border line2 = BorderFactory.createEmptyBorder(0, 0, 0, 0);
        Border border = BorderFactory.createLineBorder(Color.BLUE);
        int longitud = txtMensaje.getText().trim().length();
        longitudTxt.setText(longitud + "");
        //Terminar de configurar
        if (longitud > 160) {
            txtMensaje.setBorder(BorderFactory.createCompoundBorder(line,
                    BorderFactory.createEmptyBorder(3, 3, 3, 3)));
            JOptionPane.showMessageDialog(null, "Mensaje debe ser menor a 160 caracteres", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            txtMensaje.setBorder(BorderFactory.createCompoundBorder(border,
                    BorderFactory.createEmptyBorder(3, 3, 3, 3)));
        }
    }//GEN-LAST:event_txtMensajeKeyTyped

    public static void iniciar() {
        Mensaje m = null;
        m = ControladorAltiria.obtenerMensaje();
        if (m != null) {
            txtCorreoMensaje.setText(m.getCorreo());
            txtPasswordMensaje.setText(m.getContrasena());
            txtMensaje.setText(m.getMensaje());
            longitudTxt.setText(m.getMensaje().trim().length() + "");
            //System.out.println(m.getCorreo()+" , "+m.getContrasena());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMensaje2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel longitudTxt;
    private static javax.swing.JTextField txtCorreoMensaje;
    private static javax.swing.JTextArea txtMensaje;
    private static javax.swing.JPasswordField txtPasswordMensaje;
    // End of variables declaration//GEN-END:variables
}
